version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge 

services:
  SimpleWordASP:
    image: simplewordasp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=blogdb;username=bloguser;password=bloguser"
    networks:
      - dockerapi-dev  
  
  